'use strict';

const fs = require('fs-extra');
const path = require('path');

const db = require('../db');
const validators = require('../utils/validators');

/**
 * Default values for the form-driven serverDZ.cfg generator.
 * The structure is intentionally flat so the frontend form can render it generically.
 */
const DEFAULT_CONFIG = {
  hostname: 'My DayZ Server',
  password: '',
  passwordAdmin: '',
  maxPlayers: 60,
  verifySignatures: 2,
  forceSameBuild: 1,
  disableVoN: 0,
  vonCodecQuality: 20,
  disable3rdPerson: 0,
  disableCrosshair: 0,
  serverTime: 'SystemTime',
  serverTimeAcceleration: 12,
  serverNightTimeAcceleration: 1,
  serverTimePersistent: 1,
  guaranteedUpdates: 1,
  loginQueueConcurrentPlayers: 5,
  loginQueueMaxPlayers: 500,
  instanceId: 1,
  storageAutoFix: 1,
  motd: ['Welcome to my DayZ server!', 'Have fun and play fair.'],
  motdInterval: 1,
  steamQueryPort: 27016,
  enableMouseAndKeyboard: 1,
  serverFpsLimit: 60,
  // Mission used by the server
  missionTemplate: 'dayzOffline.chernarusplus',
};

function getStmt() {
  return db.get();
}

function loadConfigPayload(serverId) {
  const row = getStmt()
    .prepare('SELECT payload FROM server_configs WHERE server_id = ?')
    .get(serverId);
  if (!row) return JSON.parse(JSON.stringify(DEFAULT_CONFIG));
  try {
    return Object.assign({}, DEFAULT_CONFIG, JSON.parse(row.payload));
  } catch (_) {
    return JSON.parse(JSON.stringify(DEFAULT_CONFIG));
  }
}

function saveConfigPayload(serverId, payload) {
  const merged = Object.assign({}, DEFAULT_CONFIG, payload || {});
  validateConfig(merged);
  const json = JSON.stringify(merged);
  getStmt()
    .prepare(
      `INSERT INTO server_configs (server_id, payload, updated_at)
       VALUES (?, ?, CURRENT_TIMESTAMP)
       ON CONFLICT(server_id) DO UPDATE SET payload = excluded.payload, updated_at = CURRENT_TIMESTAMP`
    )
    .run(serverId, json);
  return merged;
}

function validateConfig(cfg) {
  validators.assert(typeof cfg.hostname === 'string' && cfg.hostname.length > 0, 'hostname is required');
  validators.assert(Number.isFinite(Number(cfg.maxPlayers)) && cfg.maxPlayers > 0 && cfg.maxPlayers <= 200, 'maxPlayers must be 1-200');
  validators.assert([0, 1, 2].includes(Number(cfg.verifySignatures)), 'verifySignatures must be 0, 1 or 2');
  validators.assert([0, 1].includes(Number(cfg.disable3rdPerson)), 'disable3rdPerson must be 0 or 1');
  validators.assert(Number(cfg.steamQueryPort) > 0 && Number(cfg.steamQueryPort) < 65536, 'steamQueryPort invalid');
  validators.assert(/^[A-Za-z0-9_\.\-]+$/.test(cfg.missionTemplate), 'missionTemplate has invalid characters');
  return true;
}

/**
 * Render a serverDZ.cfg file string from a config payload.
 *
 * @param {object} cfg
 * @returns {string}
 */
function renderServerDZ(cfg) {
  const c = Object.assign({}, DEFAULT_CONFIG, cfg || {});
  const motdLines = Array.isArray(c.motd) ? c.motd : [String(c.motd || '')];

  const lines = [];
  lines.push('// serverDZ.cfg - generated by DayZ Manager');
  lines.push('// Last updated: ' + new Date().toISOString());
  lines.push('');
  lines.push(`hostname = "${validators.sanitizeCfgString(c.hostname)}";`);
  lines.push(`password = "${validators.sanitizeCfgString(c.password)}";`);
  lines.push(`passwordAdmin = "${validators.sanitizeCfgString(c.passwordAdmin)}";`);
  lines.push(`maxPlayers = ${Number(c.maxPlayers)};`);
  lines.push(`verifySignatures = ${Number(c.verifySignatures)};`);
  lines.push(`forceSameBuild = ${Number(c.forceSameBuild)};`);
  lines.push(`disableVoN = ${Number(c.disableVoN)};`);
  lines.push(`vonCodecQuality = ${Number(c.vonCodecQuality)};`);
  lines.push(`disable3rdPerson = ${Number(c.disable3rdPerson)};`);
  lines.push(`disableCrosshair = ${Number(c.disableCrosshair)};`);
  lines.push(`serverTime = "${validators.sanitizeCfgString(c.serverTime)}";`);
  lines.push(`serverTimeAcceleration = ${Number(c.serverTimeAcceleration)};`);
  lines.push(`serverNightTimeAcceleration = ${Number(c.serverNightTimeAcceleration)};`);
  lines.push(`serverTimePersistent = ${Number(c.serverTimePersistent)};`);
  lines.push(`guaranteedUpdates = ${Number(c.guaranteedUpdates)};`);
  lines.push(`loginQueueConcurrentPlayers = ${Number(c.loginQueueConcurrentPlayers)};`);
  lines.push(`loginQueueMaxPlayers = ${Number(c.loginQueueMaxPlayers)};`);
  lines.push(`instanceId = ${Number(c.instanceId)};`);
  lines.push(`storageAutoFix = ${Number(c.storageAutoFix)};`);
  lines.push(`steamQueryPort = ${Number(c.steamQueryPort)};`);
  lines.push(`enableMouseAndKeyboard = ${Number(c.enableMouseAndKeyboard)};`);
  lines.push(`serverFpsLimit = ${Number(c.serverFpsLimit)};`);
  lines.push('');
  lines.push('class Missions');
  lines.push('{');
  lines.push('    class DayZ');
  lines.push('    {');
  lines.push(`        template = "${validators.sanitizeCfgString(c.missionTemplate)}";`);
  lines.push('    };');
  lines.push('};');
  lines.push('');
  lines.push('motd[] = {');
  motdLines.forEach((m, i) => {
    lines.push(`    "${validators.sanitizeCfgString(m)}"${i === motdLines.length - 1 ? '' : ','}`);
  });
  lines.push('};');
  lines.push(`motdInterval = ${Number(c.motdInterval)};`);
  lines.push('');
  return lines.join('\n');
}

/**
 * Persist serverDZ.cfg to disk inside the server's install directory.
 * @param {string} installDir
 * @param {object} cfg
 */
async function writeServerDZ(installDir, cfg) {
  const dst = path.join(installDir, 'serverDZ.cfg');
  await fs.ensureDir(installDir);
  await fs.writeFile(dst, renderServerDZ(cfg), 'utf8');
  return dst;
}

module.exports = {
  DEFAULT_CONFIG,
  loadConfigPayload,
  saveConfigPayload,
  renderServerDZ,
  writeServerDZ,
  validateConfig,
};
